/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fincaganadera;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author BlackHawk
 */
public class MoverVacas extends javax.swing.JFrame {
    
    public MoverVacas() {
        
        try {
         initComponents();
        comboPotreros();
        llegadaComboPotreros();
        mostrarMatriz(NucleoFincaGanadera.Potreros); 
        ListaPotrerosLL.setSelectedItem(null);
        ListaPotreros.setSelectedItem(null);
        
        } catch (Exception Error) {
            System.out.println(Error.getMessage());
        }
       
        
        
        
    }
        public void llegadaComboPotreros(){
        ListaPotrerosLL.addItem("Potrero 1");
        ListaPotrerosLL.addItem("Potrero 2");
        ListaPotrerosLL.addItem("Potrero 3");
        ListaPotrerosLL.addItem("Potrero 4");
        ListaPotrerosLL.addItem("Potrero 5");
        ListaPotrerosLL.addItem("Potrero 6");
        ListaPotrerosLL.addItem("Potrero 7");
        ListaPotrerosLL.addItem("Potrero 8");
        
    }
    public void comboPotreros(){
        ListaPotreros.addItem("Potrero 1");
        ListaPotreros.addItem("Potrero 2");
        ListaPotreros.addItem("Potrero 3");
        ListaPotreros.addItem("Potrero 4");
        ListaPotreros.addItem("Potrero 5");
        ListaPotreros.addItem("Potrero 6");
        ListaPotreros.addItem("Potrero 7");
        ListaPotreros.addItem("Potrero 8");
    }
    public void comboVacas(int potrero ){
        
           for(int i =0; i<NucleoFincaGanadera.Potreros.length;i++){
               if(NucleoFincaGanadera.Potreros[i][potrero]!=null){
               ListaVacas.addItem(NucleoFincaGanadera.Potreros[i][potrero]);
               }
               
               
           }
    
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ListaPotreros = new javax.swing.JComboBox<>();
        ListaVacas = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        ListaPotrerosLL = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        Mover = new javax.swing.JButton();
        btn_atrasM = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Seleccione el potrero");

        ListaPotreros.setMaximumRowCount(10);
        ListaPotreros.setSelectedItem(null);
        ListaPotreros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaPotrerosActionPerformed(evt);
            }
        });

        ListaVacas.setMaximumRowCount(10);
        ListaVacas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaVacasActionPerformed(evt);
            }
        });

        jLabel2.setText("Seleccione la vaca");

        ListaPotrerosLL.setMaximumRowCount(10);

        jLabel3.setText("Potrero de destino");

        Mover.setText("Mover");
        Mover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MoverActionPerformed(evt);
            }
        });

        btn_atrasM.setText("Atras");
        btn_atrasM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_atrasMActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Potrero 1", "Potrero 2", "Potrero 3", "Potrero 4", "Potrero 5", "Potrero 6", "Potrero 7", "Potrero 8"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_atrasM))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ListaPotreros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(217, 217, 217)
                                        .addComponent(jLabel3)
                                        .addGap(26, 26, 26)
                                        .addComponent(ListaPotrerosLL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ListaVacas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Mover)
                                        .addGap(13, 13, 13)))))))
                .addContainerGap(271, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(btn_atrasM)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(ListaPotreros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ListaPotrerosLL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ListaVacas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(Mover)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(288, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(124, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void ListaPotrerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaPotrerosActionPerformed
        
            if(ListaPotreros.getSelectedItem().equals("Potrero 1")){
               ListaVacas.removeAllItems();
                comboVacas(0);
               
               ListaVacas.setSelectedItem(null);
            }
            if(ListaPotreros.getSelectedItem().equals("Potrero 2")){
                ListaVacas.removeAllItems();
                comboVacas(1);
               ListaVacas.setSelectedItem(null);
            }
            if(ListaPotreros.getSelectedItem().equals("Potrero 3")){
                 ListaVacas.removeAllItems();
               comboVacas(2);
               ListaVacas.setSelectedItem(null);
            }
            if(ListaPotreros.getSelectedItem().equals("Potrero 4")){
                 ListaVacas.removeAllItems();
               comboVacas(3);
               ListaVacas.setSelectedItem(null);
            }
            if(ListaPotreros.getSelectedItem().equals("Potrero 5")){
                 ListaVacas.removeAllItems();
               comboVacas(4);
               ListaVacas.setSelectedItem(null);
            }
            if(ListaPotreros.getSelectedItem().equals("Potrero 6")){
                 ListaVacas.removeAllItems();
               comboVacas(5);
               ListaVacas.setSelectedItem(null);
            }
            if(ListaPotreros.getSelectedItem().equals("Potrero 7")){
                 ListaVacas.removeAllItems();
               comboVacas(6);
               ListaVacas.setSelectedItem(null);
            }
            if(ListaPotreros.getSelectedItem().equals("Potrero 8")){
                ListaVacas.removeAllItems();
               comboVacas(7);
               ListaVacas.setSelectedItem(null);
            }
        
    }//GEN-LAST:event_ListaPotrerosActionPerformed

    private void ListaVacasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaVacasActionPerformed
     
    }//GEN-LAST:event_ListaVacasActionPerformed

    private void btn_atrasMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_atrasMActionPerformed
       FincaGanadera ventanaPrincipal = new FincaGanadera();
        ventanaPrincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_atrasMActionPerformed

    private void MoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MoverActionPerformed
        int PotreroP = ListaPotreros.getSelectedIndex();
        int Vaca = ListaVacas.getSelectedIndex();
        int PotreroLL = ListaPotrerosLL.getSelectedIndex();
        System.out.println("potrero p " + PotreroP + " vaca " + Vaca + " Potrero llegada " + PotreroLL);
        Mover(PotreroP,Vaca,PotreroLL);
        
        
        actualizarMatriz();
        mostrarMatriz(NucleoFincaGanadera.Potreros);
        
        ListaPotrerosLL.setSelectedItem(null);
        ListaVacas.setSelectedItem(null);
        ListaPotreros.setSelectedItem(null);
        
        
        
        
        mostrarMatriz(NucleoFincaGanadera.Potreros);
    }//GEN-LAST:event_MoverActionPerformed
    
    public static void Mover(int potreroP, int animalP,int potreroLL){
        
         for(int i = 0; i<NucleoFincaGanadera.Potreros.length;i++){
              
               
               if(NucleoFincaGanadera.Potreros[i][potreroLL]==null){
                   NucleoFincaGanadera.Potreros [i][potreroLL] = NucleoFincaGanadera.Potreros[animalP][potreroP];
                   NucleoFincaGanadera.Potreros[animalP][potreroP] = null;
                }
               
           
           }
            
            
    
    }
    public static void actualizarMatriz(){
        try {
            
         for(int i = 0; i<NucleoFincaGanadera.Potreros.length;i++){
            for(int j = 0; j<NucleoFincaGanadera.Potreros[i].length;j++){
                if(i!=NucleoFincaGanadera.Potreros.length-1){
                    
                    if(NucleoFincaGanadera.Potreros[i][j]==null){
                    NucleoFincaGanadera.Potreros[i][j] = NucleoFincaGanadera.Potreros[i+1][j];
                    NucleoFincaGanadera.Potreros[i+1][j]=null;
                    
                    }
                    
                    
                    
                }else{
                break;
                }
                System.out.print(NucleoFincaGanadera.Potreros[i][j]+"|");
            }
            System.out.println("");
        }   
        } catch (Exception Error) {
            System.out.println(Error.getMessage());
        }
        
        
        
       
    
    }
    
    public void mostrarMatriz(String matriz[][]){
        DefaultTableModel model =(DefaultTableModel) jTable1.getModel();
        model.setRowCount(NucleoFincaGanadera.Potreros.length);
        model.setColumnCount(NucleoFincaGanadera.Potreros[0].length);
        
        for(int i = 0; i<NucleoFincaGanadera.Potreros.length;i++){
            for(int j = 0; j<NucleoFincaGanadera.Potreros[i].length;j++){
            
            jTable1.setValueAt(NucleoFincaGanadera.Potreros[i][j], i, j);
            }
        
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MoverVacas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MoverVacas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MoverVacas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MoverVacas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MoverVacas().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ListaPotreros;
    private javax.swing.JComboBox<String> ListaPotrerosLL;
    private javax.swing.JComboBox<String> ListaVacas;
    private javax.swing.JButton Mover;
    private javax.swing.JButton btn_atrasM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
